name: Update Contribution Chart

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pipipi-dev/gcchart@v1
        with:
          github_user_name: dalton150
          github_token: ${{ secrets.GH_PAT || github.token }}
          outputs: |
            contributions.svg?theme=dark&style=clean&period=90&granularity=day&cumulative=false
          target_branch: output
          commit_message: "chore: update contribution chart"
